language: python

# 3.5-dev because of http://bugs.python.org/issue25131
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7.6
      env: TOXENV=py27
      # This is used by Ubuntu Trusty
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5-dev
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - python: 3.5
      env: TOXENV=pylint
before_install:
  - python --version
  - uname -a
  - lsb_release -a
  - sudo apt-get -qq update
  - sudo apt-get install -y enchant
install:
  - pip install -U setuptools
  - pip install tox coverage coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - coverage --version
script:
    # Test install with current version of setuptools
  - pip install .
  - tox -e coverage-erase,$TOXENV
after_success:
  - tox -e coveralls
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: always
    on_failure: always

